// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AsideBar: typeof import('./src/components/favorSearchAside/favorSearchAside.vue')['default']
    BackNavBar: typeof import('./src/components/backNavBar/backNavBar.vue')['default']
    DetailSection: typeof import('./src/components/detail-section/detailSection.vue')['default']
    DropdwonSelect: typeof import('./src/components/dropdown-select/dropdwonSelect.vue')['default']
    FavorSearchAside: typeof import('./src/components/favorSearchAside/favorSearchAside.vue')['default']
    FavorSearchImg: typeof import('./src/components/favorSearchImg/favorSearchImg.vue')['default']
    FavorSearchItem: typeof import('./src/components/favorSearchItem/favorSearchItem.vue')['default']
    FavorSearchTitle: typeof import('./src/components/favorSearchTitle/favorSearchTitle.vue')['default']
    FovarSearchInfo: typeof import('./src/components/fovarSearchInfo/fovarSearchInfo.vue')['default']
    HouseItemV3: typeof import('./src/components/house-item-v3/houseItemV3.vue')['default']
    HouseItemV9: typeof import('./src/components/house-item-v9/houseItemV9.vue')['default']
    Loading: typeof import('./src/components/loading/loading.vue')['default']
    MsgTip: typeof import('./src/components/msgTip/msgTip.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBar: typeof import('./src/components/searchBar/searchBar.vue')['default']
    SideBar: typeof import('./src/components/sideBar/sideBar.vue')['default']
    TabBar: typeof import('./src/components/tabBar/tabBar.vue')['default']
    TabBar1: typeof import('./src/components/tabBar/tabBar.vue')['default']
    TabControl: typeof import('./src/components/tab-control/tab-control.vue')['default']
    TabSelect: typeof import('./src/components/tabSelect/tabSelect.vue')['default']
    TabSelectItem: typeof import('./src/components/tabSelectItem/tabSelectItem.vue')['default']
    VanButton: typeof import('vant/es')['Button']
    VanCalendar: typeof import('vant/es')['Calendar']
    VanCell: typeof import('vant/es')['Cell']
    VanDropdownItem: typeof import('vant/es')['DropdownItem']
    VanDropdownMenu: typeof import('vant/es')['DropdownMenu']
    VanIcon: typeof import('vant/es')['Icon']
    VanIndexAnchor: typeof import('vant/es')['IndexAnchor']
    VanIndexBar: typeof import('vant/es')['IndexBar']
    VanNavBar: typeof import('vant/es')['NavBar']
    VanRate: typeof import('vant/es')['Rate']
    VanSearch: typeof import('vant/es')['Search']
    VanSidebar: typeof import('vant/es')['Sidebar']
    VanSidebarItem: typeof import('vant/es')['SidebarItem']
    VanSticky: typeof import('vant/es')['Sticky']
    VanSwipe: typeof import('vant/es')['Swipe']
    VanSwipeItem: typeof import('vant/es')['SwipeItem']
    VanTab: typeof import('vant/es')['Tab']
    VanTabbar: typeof import('vant/es')['Tabbar']
    VanTabbarItem: typeof import('vant/es')['TabbarItem']
    VanTabs: typeof import('vant/es')['Tabs']
    VanTag: typeof import('vant/es')['Tag']
    VantTabBar: typeof import('./src/components/tabBar/vantTabBar.vue')['default']
    ViewHouseBtns: typeof import('./src/components/viewHouseBtns/viewHouseBtns.vue')['default']
  }
}
